import { Call } from '../types';

export const mockCallData: Call[] = [
    {
        id: 'call-1',
        operatorId: 'op-1',
        operatorName: 'Ivan Ivanov',
        date: '2024-12-01',
        rating: 5,
        duration: 120,
        callType: 'Inbound',
        comment: 'Great customer service!',
    },
    {
        id: 'call-2',
        operatorId: 'op-2',
        operatorName: 'Petr Petrov',
        date: '2024-12-02',
        rating: 4,
        duration: 150,
        callType: 'Outbound',
        comment: 'Need to improve clarity.',
    },
    {
        id: 'call-3',
        operatorId: 'op-3',
        operatorName: 'Maria Sokolova',
        date: '2024-12-03',
        rating: 3,
        duration: 180,
        callType: 'Inbound',
        comment: 'Customer had issues with the product.',
    },
    {
        id: 'call-4',
        operatorId: 'op-1',
        operatorName: 'Ivan Ivanov',
        date: '2024-12-04',
        rating: 4,
        duration: 110,
        callType: 'Outbound',
        comment: 'Resolved most issues.',
    },
    {
        id: 'call-5',
        operatorId: 'op-2',
        operatorName: 'Petr Petrov',
        date: '2024-12-05',
        rating: 5,
        duration: 130,
        callType: 'Inbound',
        comment: 'Customer is satisfied.',
    },
    {
        id: 'call-6',
        operatorId: 'op-3',
        operatorName: 'Maria Sokolova',
        date: '2024-12-06',
        rating: 2,
        duration: 140,
        callType: 'Outbound',
        comment: 'Unresolved issue, further follow-up needed.',
    },
    {
        id: 'call-7',
        operatorId: 'op-1',
        operatorName: 'Ivan Ivanov',
        date: '2024-12-07',
        rating: 4,
        duration: 100,
        callType: 'Inbound',
        comment: 'Customer was pleased with the service.',
    },
    {
        id: 'call-8',
        operatorId: 'op-2',
        operatorName: 'Petr Petrov',
        date: '2024-12-08',
        rating: 3,
        duration: 160,
        callType: 'Outbound',
        comment: 'Call transferred to another department.',
    },
    {
        id: 'call-9',
        operatorId: 'op-3',
        operatorName: 'Maria Sokolova',
        date: '2024-12-09',
        rating: 4,
        duration: 145,
        callType: 'Inbound',
        comment: 'Resolved the customer’s issue quickly.',
    },
    {
        id: 'call-10',
        operatorId: 'op-1',
        operatorName: 'Ivan Ivanov',
        date: '2024-12-10',
        rating: 5,
        duration: 110,
        callType: 'Outbound',
        comment: 'Successful call, customer happy with the outcome.',
    },
];
